version: "3.4"

networks:
    frontend:
    backend:

services:
    catalogevent:
        build:
            context: .\EventCatalogApi
            dockerfile: Dockerfile
        image: event/catalog
        environment:
            DatabaseServer: mssqlserver
            DatabaseName: catalogeventdb
            DatabaseUser: sa
            DatabaseUserPassword: EventAPI!
            ExternalCatalogBaseUrl: http://localhost:33247
        container_name: catalogeventapi
        ports:
            - "33247:80"
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver

    tokenserver:
        build: 
            context: .\TokenServiceApi
            dockerfile: Dockerfile
        environment: 
            ASPNETCORE_ENVIRONMENT: Development 
            MvcClient: http://localhost:50923
        container_name: tokenservice
        ports:
            - "5022:80"
        networks:
            - backend
            - frontend 
        depends_on:
            - mssqlserver

    webmvc:
        build: 
            context: .\WebMvc
            dockerfile: Dockerfile
        environment: 
            ASPNETCORE_ENVIRONMENT: Development 
            CatalogUrl: http://catalogevent
            IdentityUrl: http://10.0.0.223:5022
            CallBackUrl: http://localhost:50923
        container_name: webevent
        ports:
            - "50923:80"
        networks:
            - frontend 
        depends_on:
            - catalogevent
            - tokenserver
   
    mssqlserver:
        image: "microsoft/mssql-server-linux:latest"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: EventAPI!
        container_name: catalogeventdb
        ports:
            - "1447:1433"
        networks:
            - backend
